package com.practice.java8.streams;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapVsFlatMapDemo {

	public static void main(String[] args) {
		// making the array list object
		ArrayList<String> fruit = new ArrayList<>();
		fruit.add("Apple");
		fruit.add("mango");
		fruit.add("pineapple");
		fruit.add("kiwi");
		System.out.println("List of fruit-" + fruit);

		// lets use map() to convert list of fruit
		List<Integer> list = fruit.stream().map(s -> s.length()).collect(Collectors.toList());
		System.out.println("List generated by map-" + list);

		// flatMap
		
		// making the arraylist object of List of Integer
		List<List<Integer>> number = new ArrayList<>();

		// adding the elements to number arraylist
		number.add(Arrays.asList(1, 2));
		number.add(Arrays.asList(3, 4));
		number.add(Arrays.asList(5, 6));
		number.add(Arrays.asList(7, 8));

		System.out.println("List of list-" + number);

		// using flatmap() to flatten this list
		List<Integer> flatList = number.stream().flatMap(numlist -> numlist.stream()).collect(Collectors.toList());

		// printing the list
		System.out.println("List generate by flatMap-" + flatList);

	}

}
